[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
source = ["pv_tool_logic"]

[tool.coverage.report]
show_missing = true

[tool.poetry]
name = "pv_tool_logic"
version = "1.1.0"
description = "Proevenverzamelingtool voor het opstellen van lokale of regionale proevenverzamelingen voor het bepalen van geotechnische parameters."
authors = [
    "Tjalda Deenekamp <tjalda.deenekamp@arcadis.nl>",
    "Leo Kwakman <leo.kwakman@arcadis.com>",
    "Nathan Gebraad <nathan.gebraad@arcadis.com>"
]
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/PVorganization/PV-tool"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

[tool.poetry.dependencies]
python = "^3.11"
pandas = "<3.0.0"
#numpy = "^2.4.4" # mogelijk aanpassen als PV-app wordt gebruikt i.p.v. de notebook.
numpy = ">=1.24.0,<2.0.0"
scipy = "^1.17.1"
matplotlib = "^3.10.8"
plotly = "^6.6.0"
openpyxl = "^3.1.5"
xlwings = "0.33.16"
gitpython = "^3.1.46"
pandas-schema = "^0.3.6"
xlsxwriter = "^3.2.9"
reportlab = "^4.4.10"
kaleido = "^1.2.0"
ipywidgets = "^8.1.8"
ipyfilechooser = "^0.6.0"
ipython = "^9.12.0"
pillow = "^12.1.1"
