TWO_PERC_COLUMNS = ['PV_NAAM', 'TXT_SS_S\'_2%', 'TXT_SS_T_2%']

FIVE_PERC_COLUMNS = ['PV_NAAM', 'TXT_SS_S\'_5%', 'TXT_SS_T_5%']

FIFTEEN_PERC_COLUMNS = ['PV_NAAM', 'TXT_SS_S\'_15%', 'TXT_SS_T_15%']

PIEKSTERKTE_COLUMNS = ['PV_NAAM', 'TXT_SS_S\'_BIJ_T_PIEK', 'TXT_SS_T_PIEK']

EINDSTERKTE_COLUMNS = ['PV_NAAM', 'TXT_SS_S\'_BIJ_T_EIND', 'TXT_SS_T_EIND']

TEXTUAL_NAMES = {
    '2% rek': TWO_PERC_COLUMNS,
    '5% rek': FIVE_PERC_COLUMNS,
    '15% rek': FIFTEEN_PERC_COLUMNS,
    'pieksterkte': PIEKSTERKTE_COLUMNS,
    'eindsterkte': EINDSTERKTE_COLUMNS,
}

NEW_COLUMN_NAMES = ['PV_NAAM', 'S\'', 'T']
