TWO_PERC_COLUMNS = ['ALG__BORING_MONSTERNR', 'PV_NAAM', 'TXT_SS_S\'_2%', 'TXT_SS_T_2%']

FIVE_PERC_COLUMNS = ['ALG__BORING_MONSTERNR', 'PV_NAAM', 'TXT_SS_S\'_5%', 'TXT_SS_T_5%']

FIFTEEN_PERC_COLUMNS = ['ALG__BORING_MONSTERNR', 'PV_NAAM', 'TXT_SS_S\'_15%', 'TXT_SS_T_15%']

PIEKSTERKTE_COLUMNS = ['ALG__BORING_MONSTERNR', 'PV_NAAM', 'TXT_SS_S\'_BIJ_T_PIEK', 'TXT_SS_T_PIEK']

EINDSTERKTE_COLUMNS = ['ALG__BORING_MONSTERNR', 'PV_NAAM', 'TXT_SS_S\'_BIJ_T_EIND', 'TXT_SS_T_EIND']