#------------------------------------SHANSEP----------------------------------------
#------------------------------------TXT-----------------------------------------

TWO_PERC_COLUMNS = ['PV_NAAM', 'ALG__REGEL', 'TXT_SS_T_2%', 'ANA_TXT_MAX_VERTICALE_CONSOLIDATIE_SPANNING', 'ANA_TXT_CONSOLIDATIE_TYPE_REKEN', 'OCR_TXT', 'ANA_TERREINSPANNING']

FIVE_PERC_COLUMNS = ['PV_NAAM', 'ALG__REGEL', 'TXT_SS_T_5%', 'ANA_TXT_MAX_VERTICALE_CONSOLIDATIE_SPANNING', 'ANA_TXT_CONSOLIDATIE_TYPE_REKEN', 'OCR_TXT', 'ANA_TERREINSPANNING']

FIFTEEN_PERC_COLUMNS = ['PV_NAAM', 'ALG__REGEL', 'TXT_SS_T_15%', 'ANA_TXT_MAX_VERTICALE_CONSOLIDATIE_SPANNING', 'ANA_TXT_CONSOLIDATIE_TYPE_REKEN', 'OCR_TXT', 'ANA_TERREINSPANNING']

PIEKSTERKTE_COLUMNS = ['PV_NAAM', 'ALG__REGEL', 'TXT_SS_T_BIJ_T_PIEK', 'ANA_TXT_MAX_VERTICALE_CONSOLIDATIE_SPANNING', 'ANA_TXT_CONSOLIDATIE_TYPE_REKEN', 'OCR_TXT', 'ANA_TERREINSPANNING']

EINDSTERKTE_COLUMNS = ['PV_NAAM', 'ALG__REGEL', 'TXT_SS_T_BIJ_T_EIND', 'ANA_TXT_MAX_VERTICALE_CONSOLIDATIE_SPANNING', 'ANA_TXT_CONSOLIDATIE_TYPE_REKEN', 'OCR_TXT', 'ANA_TERREINSPANNING']

TEXTUAL_NAMES = {
    '2% rek': TWO_PERC_COLUMNS,
    '5% rek': FIVE_PERC_COLUMNS,
    '15% rek': FIFTEEN_PERC_COLUMNS,
    'pieksterkte': PIEKSTERKTE_COLUMNS,
    'eindsterkte': EINDSTERKTE_COLUMNS,
}

NEW_COLUMN_NAMES = ['PV_NAAM', 'regel nr', 'S\'v', 'Su', 'consolidatietype', 'OCR', 'terreinspanning']

# -------------------------------------- DSS ---------------------------------------
# TODO onderstaande lijst bevat nog veel txt, moet dit veranderd worden naar dss?

TWO_PERC_COLUMNS_DSS = ['PV_NAAM',  'ALG__REGEL', 'ANA_DSS_MAX_CONSOLIDATIE_SPANNING', 'DSS_T_2%', 'ANA_TXT_CONSOLIDATIE_TYPE_REKEN', 'OCR_TXT', 'ANA_TERREINSPANNING']

FIVE_PERC_COLUMNS_DSS = ['PV_NAAM',  'ALG__REGEL', 'DSS_T_5%', 'ANA_DSS_MAX_CONSOLIDATIE_SPANNING', 'ANA_TXT_CONSOLIDATIE_TYPE_REKEN', 'OCR_TXT', 'ANA_TERREINSPANNING']

TEN_PERC_COLUMNS_DSS = ['PV_NAAM',  'ALG__REGEL', 'DSS_T_10%', 'ANA_DSS_MAX_CONSOLIDATIE_SPANNING', 'ANA_TXT_CONSOLIDATIE_TYPE_REKEN', 'OCR_TXT', 'ANA_TERREINSPANNING']

FIFTEEN_PERC_COLUMNS_DSS = ['PV_NAAM',  'ALG__REGEL', 'DSS_T_15%', 'ANA_DSS_MAX_CONSOLIDATIE_SPANNING', 'ANA_TXT_CONSOLIDATIE_TYPE_REKEN', 'OCR_TXT', 'ANA_TERREINSPANNING']

TWENTY_PERC_COLUMNS_DSS = ['PV_NAAM', 'ALG__REGEL', 'DSS_T_20%', 'ANA_DSS_MAX_CONSOLIDATIE_SPANNING', 'ANA_TXT_CONSOLIDATIE_TYPE_REKEN', 'OCR_TXT', 'ANA_TERREINSPANNING']

PIEKSTERKTE_COLUMNS_DSS = ['PV_NAAM', 'ALG__REGEL', 'DSS_T_BIJ_T_MAX', 'ANA_DSS_MAX_CONSOLIDATIE_SPANNING', 'ANA_TXT_CONSOLIDATIE_TYPE_REKEN', 'OCR_TXT', 'ANA_TERREINSPANNING']

EINDSTERKTE_COLUMNS_DSS = ['PV_NAAM', 'ALG__REGEL', 'DSS_T_BIJ_T_EIND', 'ANA_DSS_MAX_CONSOLIDATIE_SPANNING', 'ANA_TXT_CONSOLIDATIE_TYPE_REKEN', 'OCR_TXT', 'ANA_TERREINSPANNING']

TEXTUAL_NAMES_DSS = {
    '2% rek': TWO_PERC_COLUMNS_DSS,
    '5% rek': FIVE_PERC_COLUMNS_DSS,
    '10% rek': TEN_PERC_COLUMNS_DSS,
    '15% rek': FIFTEEN_PERC_COLUMNS_DSS,
    '20% rek': TWENTY_PERC_COLUMNS_DSS,
    'pieksterkte': PIEKSTERKTE_COLUMNS_DSS,
    'eindsterkte': EINDSTERKTE_COLUMNS_DSS,
}